name: ci

on: [push]

jobs:
  build:
    # skip releases
    if: startsWith(github.ref, '[maven-release-plugin] prepare release') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # needed for license-plugin to check last modified date of each file
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '20'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: mvn clean verify
        run: mvn -V --no-transfer-progress --batch-mode clean verify
